"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from .secret_manager import get_env_or_secret

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 載入環境變數
# 優先載入專案根目錄的 .env，然後載入後端目錄的 .env
load_dotenv(BASE_DIR.parent / '.env')  # 根目錄的 .env
load_dotenv(BASE_DIR.parent / 'backend' / '.env')  # 後端目錄的 .env
load_dotenv(BASE_DIR / '.env')  # config 目錄的 .env（如果存在）


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 優先從環境變數讀取，如果啟用了 Secret Manager，則從 Secret Manager 讀取
SECRET_KEY = get_env_or_secret(
    'DJANGO_SECRET_KEY',
    secret_id='django-secret-key',
    default='django-insecure-k#&ll@igxrfb*g=la9c9g=r_@thy06_10wywdsysaxzr2v!@el'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  # WhiteNoise 用於靜態文件服務
    'storages',  # django-storages 用於 Cloud Storage
    'cramschool',
    'account',
    'rest_framework',
    'rest_framework_simplejwt',  # JWT 認證
    'rest_framework_simplejwt.token_blacklist',  # JWT token 黑名單
    'corsheaders',  # CORS 支援
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise 靜態文件中間件（放在 SecurityMiddleware 之後）
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 中間件應該放在 CommonMiddleware 之前
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'account.middleware.AuditLogMiddleware',  # 操作記錄中間件
    # 'account.middleware.PermissionCheckMiddleware',  # 權限檢查中間件（可選，根據需要啟用）
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'
# 告訴 Django 在哪裡尋找靜態檔案 (例如：CSS, JS, 圖片)
STATICFILES_DIRS = [
    # 假設你的 Vue build 輸出路徑是 frontend/dist 或 frontend/build
    os.path.join(BASE_DIR, "frontend/dist/static"), # 根據你的前端打包結果調整路徑
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # 確保 templates 資料夾在 DIRS 列表中
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_ENGINE = os.getenv('DATABASE_ENGINE', 'django.db.backends.sqlite3')

# 支持 Cloud SQL 連接（通過 Unix Socket 或 TCP）
if os.getenv('CLOUD_SQL_CONNECTION_NAME'):
    # Cloud SQL 通過 Unix Socket 連接
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': get_env_or_secret('DATABASE_NAME', secret_id='database-name', default=''),
            'USER': get_env_or_secret('DATABASE_USER', secret_id='database-user', default=''),
            'PASSWORD': get_env_or_secret('DATABASE_PASSWORD', secret_id='database-password', default=''),
            'HOST': f'/cloudsql/{os.getenv("CLOUD_SQL_CONNECTION_NAME")}',
        }
    }
elif DATABASE_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': DATABASE_ENGINE,
            'NAME': BASE_DIR / os.getenv('DATABASE_NAME', 'db.sqlite3'),
        }
    }
else:
    # PostgreSQL 或其他資料庫（TCP 連接）
    DATABASES = {
        'default': {
            'ENGINE': DATABASE_ENGINE,
            'NAME': get_env_or_secret('DATABASE_NAME', secret_id='database-name', default=''),
            'USER': get_env_or_secret('DATABASE_USER', secret_id='database-user', default=''),
            'PASSWORD': get_env_or_secret('DATABASE_PASSWORD', secret_id='database-password', default=''),
            'HOST': os.getenv('DATABASE_HOST', 'localhost'),
            'PORT': os.getenv('DATABASE_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'zh-hant')

TIME_ZONE = os.getenv('TIME_ZONE', 'Asia/Taipei')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 生產環境靜態文件收集目錄

# WhiteNoise 配置
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploaded files)
# 如果設置了 GS_BUCKET_NAME，使用 Cloud Storage；否則使用本地文件系統
GS_BUCKET_NAME = os.getenv('GS_BUCKET_NAME', '')  # Cloud Storage bucket 名稱

if GS_BUCKET_NAME:
    # 使用 Cloud Storage 存儲媒體文件
    DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
    GS_PROJECT_ID = os.getenv('GS_PROJECT_ID', os.getenv('GCP_PROJECT_ID', ''))
    GS_DEFAULT_ACL = 'publicRead'  # 公開讀取權限
    GS_FILE_OVERWRITE = False  # 不覆蓋同名文件
    GS_QUERYSTRING_AUTH = False  # URL 不需要認證參數
    
    # MEDIA_URL 設置為 Cloud Storage 的公開 URL
    MEDIA_URL = os.getenv(
        'MEDIA_URL',
        f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'
    )
    MEDIA_ROOT = ''  # 使用 Cloud Storage 時不需要本地根目錄
else:
    # 使用本地文件系統（開發環境）
    MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
    MEDIA_ROOT = os.path.join(BASE_DIR, os.getenv('MEDIA_ROOT', 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 自訂用戶模型
AUTH_USER_MODEL = 'account.CustomUser'

# CORS 設定
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True').lower() == 'true'
CORS_ALLOW_CREDENTIALS = True  # 允許發送 cookies

# 如果 CORS_ALLOW_ALL_ORIGINS 為 False，則使用 CORS_ALLOWED_ORIGINS
if not CORS_ALLOW_ALL_ORIGINS:
    cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,http://127.0.0.1:3000')
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(',')]

# REST Framework 設定
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # 使用 JWT 認證
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # 開發階段，生產環境請改為適當的權限
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# JWT 設定
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME_HOURS', '1'))),  # Access token 有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME_DAYS', '7'))),  # Refresh token 有效期
    'ROTATE_REFRESH_TOKENS': os.getenv('JWT_ROTATE_REFRESH_TOKENS', 'True').lower() == 'true',  # 刷新時輪換 refresh token
    'BLACKLIST_AFTER_ROTATION': os.getenv('JWT_BLACKLIST_AFTER_ROTATION', 'True').lower() == 'true',  # 輪換後將舊 token 加入黑名單
    'UPDATE_LAST_LOGIN': True,  # 更新最後登入時間
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),  # 使用 Bearer token
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
}

# CSRF 設置
csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins.split(',')]

# Session 設置
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_HTTPONLY = os.getenv('SESSION_COOKIE_HTTPONLY', 'True').lower() == 'true'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False').lower() == 'true'  # 開發環境設為 False，生產環境設為 True（HTTPS）

# 安全設置（生產環境）
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000  # 1 年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# Cloud Run 會自動設置 PORT 環境變數
PORT = os.getenv('PORT', '8080')

