# Generated by Django 5.2.7 on 2025-12-09 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='角色名稱')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.role', verbose_name='自訂角色'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', '新增'), ('update', '更新'), ('delete', '刪除'), ('view', '查看'), ('login', '登入'), ('logout', '登出'), ('other', '其他')], max_length=10, verbose_name='操作類型')),
                ('resource_type', models.CharField(max_length=100, verbose_name='資源類型')),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='資源ID')),
                ('resource_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='資源名稱')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用戶代理')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='請求數據')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='回應狀態碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='account.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '操作記錄',
                'verbose_name_plural': '操作記錄',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='account_aud_user_id_961118_idx'), models.Index(fields=['role', '-created_at'], name='account_aud_role_id_b9b6be_idx'), models.Index(fields=['action_type', '-created_at'], name='account_aud_action__d19a1c_idx'), models.Index(fields=['resource_type', '-created_at'], name='account_aud_resourc_c98b7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('page', '頁面'), ('api', 'API')], max_length=10, verbose_name='權限類型')),
                ('resource', models.CharField(max_length=200, verbose_name='資源路徑')),
                ('method', models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP 方法')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='account.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色權限',
                'verbose_name_plural': '角色權限',
                'ordering': ['role', 'permission_type', 'resource'],
                'unique_together': {('role', 'permission_type', 'resource', 'method')},
            },
        ),
    ]
