# Generated by Django 5.2.7 on 2025-12-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_role_customuser_custom_role_auditlog_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='如果為 True，用戶首次登入時必須修改密碼', verbose_name='首次登入需修改密碼'),
        ),
    ]
