# Generated by Django 5.2.7 on 2025-12-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', '系統管理員'), ('TEACHER', '老師'), ('STUDENT', '學生'), ('ACCOUNTANT', '會計')], default='STUDENT', max_length=10, verbose_name='身分/角色'),
        ),
    ]
