# Generated by Django 5.2.7 on 2025-12-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='角色代碼'),
        ),
    ]
