# Generated by Django 5.2.7 on 2025-12-05 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='課程ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, verbose_name='上課日')),
                ('fee_per_session', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每堂課收費')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='Active', max_length=10, verbose_name='課程狀態')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False, verbose_name='題目ID')),
                ('subject', models.CharField(choices=[('Eng', 'English'), ('Math', 'Math'), ('Chinese', 'Chinese'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography')], max_length=20, verbose_name='科目')),
                ('level', models.CharField(choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School'), ('VCS', 'Vocational School')], max_length=3, verbose_name='適用年級')),
                ('chapter', models.CharField(max_length=100, verbose_name='章節/單元')),
                ('content', models.TextField(verbose_name='題目內容 (Markdown + LaTeX)')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='題目圖片路徑')),
                ('correct_answer', models.TextField(verbose_name='正確答案')),
                ('difficulty', models.IntegerField(default=1, verbose_name='難度等級 (1-5)')),
            ],
            options={
                'verbose_name': '題目庫',
                'verbose_name_plural': '題目庫',
                'ordering': ['subject', 'level', 'chapter'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店家ID')),
                ('name', models.CharField(max_length=100, verbose_name='店家名稱')),
                ('business_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='營業時間')),
                ('menu_image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='菜單圖片路徑')),
            ],
            options={
                'verbose_name': '店家資訊',
                'verbose_name_plural': '店家資訊',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False, verbose_name='老師ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='帳號')),
                ('password_hash', models.CharField(max_length=255, verbose_name='密碼雜湊')),
                ('permission_level', models.CharField(choices=[('Teacher', 'Teacher'), ('Admin', 'Admin')], default='Teacher', max_length=10, verbose_name='權限等級')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡電話')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入職日期')),
            ],
            options={
                'verbose_name': '老師資料',
                'verbose_name_plural': '老師資料',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='緊急聯絡人姓名'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='緊急聯絡人電話'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡電話'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='學生ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=20, verbose_name='年級'),
        ),
        migrations.CreateModel(
            name='ExtraFee',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False, verbose_name='收費ID')),
                ('item', models.CharField(choices=[('Transport', 'Transport'), ('Meal', 'Meal'), ('Book', 'Book'), ('Other', 'Other')], max_length=20, verbose_name='收費名目')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收費金額')),
                ('fee_date', models.DateField(verbose_name='費用日期')),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partial', 'Partial')], default='Unpaid', max_length=10, verbose_name='繳費狀態')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fees', to='cramschool.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '額外收費',
                'verbose_name_plural': '額外收費',
                'ordering': ['-fee_date'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False, verbose_name='請假ID')),
                ('leave_date', models.DateField(verbose_name='請假日期')),
                ('reason', models.CharField(max_length=255, verbose_name='請假原因')),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10, verbose_name='審核狀態')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='cramschool.course', verbose_name='課程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='cramschool.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '請假記錄',
                'verbose_name_plural': '請假記錄',
                'ordering': ['-leave_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False, verbose_name='場次ID')),
                ('session_date', models.DateField(verbose_name='上課日期')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cramschool.course', verbose_name='課程')),
            ],
            options={
                'verbose_name': '上課記錄',
                'verbose_name_plural': '上課記錄',
                'ordering': ['-session_date'],
                'unique_together': {('course', 'session_date')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='作答ID')),
                ('test_name', models.CharField(max_length=100, verbose_name='測驗/作業名稱')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否答對')),
                ('scanned_file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='考卷掃描檔路徑')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='cramschool.questionbank', verbose_name='題目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cramschool.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '學生作答記錄',
                'verbose_name_plural': '學生作答記錄',
                'ordering': ['-answer_id'],
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='標籤ID')),
                ('tag_name', models.CharField(max_length=50, unique=True, verbose_name='標籤名稱')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to='cramschool.teacher', verbose_name='創建者')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤',
                'ordering': ['tag_name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='cramschool.teacher', verbose_name='授課老師'),
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('error_log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='錯誤記錄ID')),
                ('error_count', models.IntegerField(default=1, verbose_name='錯誤次數')),
                ('review_status', models.CharField(choices=[('New', 'New'), ('Reviewing', 'Reviewing'), ('Mastered', 'Mastered')], default='New', max_length=10, verbose_name='掌握狀態')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='cramschool.student', verbose_name='學生')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='cramschool.questionbank', verbose_name='錯題')),
            ],
            options={
                'verbose_name': '錯題本',
                'verbose_name_plural': '錯題本',
                'ordering': ['-error_count'],
                'unique_together': {('student', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('question_tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='關聯ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cramschool.questionbank', verbose_name='題目')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cramschool.hashtag', verbose_name='標籤')),
            ],
            options={
                'verbose_name': '題目標籤關聯',
                'verbose_name_plural': '題目標籤關聯',
                'unique_together': {('question', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False, verbose_name='出席ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Leave', 'Leave')], default='Absent', max_length=10, verbose_name='出席狀態')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='cramschool.student', verbose_name='學生')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='cramschool.sessionrecord', verbose_name='課程場次')),
            ],
            options={
                'verbose_name': '出席記錄',
                'verbose_name_plural': '出席記錄',
                'ordering': ['-session__session_date'],
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='報名ID')),
                ('enroll_date', models.DateField(verbose_name='報名日期')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='折扣百分比')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cramschool.course', verbose_name='課程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cramschool.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '學生報名',
                'verbose_name_plural': '學生報名',
                'ordering': ['-enroll_date'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
