# Generated by Django 5.2.7 on 2025-12-08 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0002_course_questionbank_store_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False, verbose_name='科目ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='科目名稱')),
                ('code', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='科目代碼')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='cramschool.subject', verbose_name='科目'),
        ),
    ]
