# Generated by Django 5.2.7 on 2025-12-09 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0003_subject_delete_store_alter_questionbank_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店家ID')),
                ('name', models.CharField(max_length=100, verbose_name='店家名稱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('menu_image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='菜單圖片路徑')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '店家',
                'verbose_name_plural': '店家',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('group_order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='團購ID')),
                ('title', models.CharField(max_length=200, verbose_name='團購標題')),
                ('order_link', models.CharField(max_length=255, unique=True, verbose_name='團購連結')),
                ('status', models.CharField(choices=[('Open', '進行中'), ('Closed', '已結束'), ('Completed', '已完成')], default='Open', max_length=20, verbose_name='狀態')),
                ('deadline', models.DateTimeField(verbose_name='截止時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_orders', to='cramschool.teacher', verbose_name='建立者')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_orders', to='cramschool.restaurant', verbose_name='店家')),
            ],
            options={
                'verbose_name': '團購',
                'verbose_name_plural': '團購',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='訂單ID')),
                ('status', models.CharField(choices=[('Pending', '待確認'), ('Confirmed', '已確認'), ('Cancelled', '已取消')], default='Pending', max_length=20, verbose_name='狀態')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='總金額')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('group_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cramschool.grouporder', verbose_name='團購')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cramschool.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='訂單項目ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='項目名稱')),
                ('quantity', models.IntegerField(default=1, verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小計')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cramschool.order', verbose_name='訂單')),
            ],
            options={
                'verbose_name': '訂單項目',
                'verbose_name_plural': '訂單項目',
                'ordering': ['order_item_id'],
            },
        ),
    ]
