# Generated by Django 5.2.7 on 2025-12-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0005_extrafee_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafee',
            name='item',
            field=models.CharField(choices=[('Tuition', '學費'), ('Transport', '交通費'), ('Meal', '餐費'), ('Book', '書籍費'), ('Other', '其他')], max_length=20, verbose_name='收費名目'),
        ),
    ]
