# Generated by Django 5.2.7 on 2025-12-09 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0006_alter_extrafee_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.CreateModel(
            name='EnrollmentPeriod',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False, verbose_name='期間ID')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否進行中')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='cramschool.studentenrollment', verbose_name='報名記錄')),
            ],
            options={
                'verbose_name': '報名期間',
                'verbose_name_plural': '報名期間',
                'ordering': ['start_date'],
            },
        ),
    ]
