# Generated by Django 5.2.7 on 2025-12-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0008_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='initial_password',
            field=models.CharField(blank=True, help_text='學生帳號的初始密碼，僅供管理員查看', max_length=50, null=True, verbose_name='初始密碼'),
        ),
    ]
