# Generated by Django 5.2.7 on 2025-12-11 07:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0010_add_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='imported_from_error_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_questions', to='cramschool.errorlog', verbose_name='來源錯題記錄'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='source',
            field=models.CharField(choices=[('teacher_created', '老師新增'), ('imported_from_error_log', '從錯題本匯入')], default='teacher_created', max_length=30, verbose_name='題目來源'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='提交ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='總分')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Graded', 'Graded')], default='Pending', max_length=10, verbose_name='狀態')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交時間')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cramschool.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '測驗提交',
                'verbose_name_plural': '測驗提交',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cramschool.assessmentsubmission', verbose_name='提交記錄'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False, verbose_name='考卷ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('is_individualized', models.BooleanField(default=False, verbose_name='是否為個別化考卷')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='開放時間')),
                ('available_until', models.DateTimeField(blank=True, null=True, verbose_name='截止時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='cramschool.course', verbose_name='課程')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('questions', models.ManyToManyField(related_name='exams', to='cramschool.questionbank', verbose_name='題目')),
            ],
            options={
                'verbose_name': '考卷',
                'verbose_name_plural': '考卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='cramschool.exam', verbose_name='考卷'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Quiz ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('is_individualized', models.BooleanField(default=False, verbose_name='是否為個別化測驗')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='cramschool.course', verbose_name='課程')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('questions', models.ManyToManyField(related_name='quizzes', to='cramschool.questionbank', verbose_name='題目')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='cramschool.quiz', verbose_name='測驗'),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='群組ID')),
                ('name', models.CharField(max_length=100, verbose_name='群組名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_groups', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('students', models.ManyToManyField(related_name='student_groups', to='cramschool.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '學生群組',
                'verbose_name_plural': '學生群組',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='student_groups',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='cramschool.studentgroup', verbose_name='學生群組'),
        ),
        migrations.AddField(
            model_name='exam',
            name='student_groups',
            field=models.ManyToManyField(blank=True, related_name='exams', to='cramschool.studentgroup', verbose_name='學生群組'),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False, verbose_name='講義ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='講義內容 (Markdown + LaTeX)')),
                ('is_individualized', models.BooleanField(default=False, verbose_name='是否為個別化講義')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='cramschool.course', verbose_name='課程')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_materials', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('questions', models.ManyToManyField(blank=True, related_name='materials', to='cramschool.questionbank', verbose_name='引用的題目')),
                ('student_groups', models.ManyToManyField(blank=True, related_name='materials', to='cramschool.studentgroup', verbose_name='學生群組')),
            ],
            options={
                'verbose_name': '上課講義',
                'verbose_name_plural': '上課講義',
                'ordering': ['-created_at'],
            },
        ),
    ]
