# Generated by Django 5.2.7 on 2025-12-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0013_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='permission_level',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Accountant', 'Accountant')], default='Teacher', help_text='此欄位用於業務邏輯，實際權限應從 user.role 獲取', max_length=10, verbose_name='權限等級'),
        ),
    ]
