# Generated by Django 5.2.7 on 2025-12-11 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0014_alter_teacher_permission_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False, verbose_name='模板ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('structure', models.JSONField(default=list, verbose_name='結構內容')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('tags', models.ManyToManyField(blank=True, related_name='templates', to='cramschool.hashtag', verbose_name='標籤')),
            ],
            options={
                'verbose_name': '內容模板',
                'verbose_name_plural': '內容模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False, verbose_name='資源ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('resource_type', models.CharField(choices=[('QUIZ', '小考'), ('EXAM', '段考卷'), ('HANDOUT', '講義'), ('DOCUMENT', '一般文件')], default='DOCUMENT', max_length=20, verbose_name='資源類型')),
                ('structure', models.JSONField(default=list, verbose_name='內容結構')),
                ('settings', models.JSONField(default=dict, verbose_name='設定 (版面/紙張)')),
                ('is_individualized', models.BooleanField(default=False, verbose_name='是否為個別化教材')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='開放時間')),
                ('available_until', models.DateTimeField(blank=True, null=True, verbose_name='截止時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_resources', to='cramschool.course', verbose_name='所屬課程')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('student_groups', models.ManyToManyField(blank=True, related_name='learning_resources', to='cramschool.studentgroup', verbose_name='可見學生群組')),
                ('tags', models.ManyToManyField(blank=True, related_name='learning_resources', to='cramschool.hashtag', verbose_name='標籤')),
            ],
            options={
                'verbose_name': '教學資源',
                'verbose_name_plural': '教學資源',
                'ordering': ['-created_at'],
            },
        ),
    ]
