# Generated by Django 5.2.7 on 2025-12-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0016_make_teacher_required_in_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='origin',
            field=models.CharField(blank=True, help_text='題目出處（例如：統測題）', max_length=200, null=True, verbose_name='出處'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='origin_detail',
            field=models.CharField(blank=True, help_text='題目來源詳細資訊（例如：101統測B）', max_length=200, null=True, verbose_name='題源'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='question_number',
            field=models.CharField(blank=True, help_text='從 Word 匯入的題號', max_length=50, null=True, verbose_name='題號'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='source',
            field=models.CharField(choices=[('teacher_created', '老師新增'), ('imported_from_error_log', '從錯題本匯入'), ('imported_from_word', '從 Word 匯入')], default='teacher_created', max_length=30, verbose_name='題目來源'),
        ),
    ]
