# Generated by Django 5.2.7 on 2025-12-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0017_questionbank_origin_questionbank_origin_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='search_text_content',
            field=models.TextField(blank=True, help_text='用於全文檢索的純文字（從 Tiptap JSON 自動提取）', null=True, verbose_name='搜尋文字內容'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='solution_content',
            field=models.JSONField(blank=True, default=dict, help_text='使用 Tiptap 編輯器創建的詳解內容，支援富文本、2D/3D 圖形', null=True, verbose_name='詳解內容 (Tiptap JSON)'),
        ),
    ]
