# Generated by Django 5.2.7 on 2025-12-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0020_mistake_images_errorlog_images_imported_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafee',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10, verbose_name='繳費狀態'),
        ),
    ]
