# Generated by Django 5.2.7 on 2025-12-18 04:39

from django.db import migrations, models


def migrate_resource_type_to_mode(apps, schema_editor):
    """將 resource_type 遷移到 mode"""
    LearningResource = apps.get_model('cramschool', 'LearningResource')
    
    # 映射關係：將舊的 resource_type 轉換為新的 mode
    type_to_mode = {
        'QUIZ': 'ONLINE_QUIZ',
        'EXAM': 'ONLINE_QUIZ',
        'HANDOUT': 'HANDOUT',
        'DOCUMENT': 'HANDOUT',
    }
    
    for resource in LearningResource.objects.all():
        if hasattr(resource, 'resource_type') and resource.resource_type:
            resource.mode = type_to_mode.get(resource.resource_type, 'HANDOUT')
            resource.save()


def reverse_migrate_mode_to_resource_type(apps, schema_editor):
    """反向遷移：將 mode 轉換回 resource_type（如果需要）"""
    LearningResource = apps.get_model('cramschool', 'LearningResource')
    
    # 反向映射
    mode_to_type = {
        'ONLINE_QUIZ': 'QUIZ',
        'HANDOUT': 'HANDOUT',
        'LEETCODE': 'DOCUMENT',
        'LISTENING_TEST': 'DOCUMENT',
        'FLASHCARD': 'DOCUMENT',
    }
    
    for resource in LearningResource.objects.all():
        if hasattr(resource, 'mode') and resource.mode:
            # 注意：這個反向遷移可能不完全準確，因為 mode 比 resource_type 更細緻
            pass  # 反向遷移可能不需要，因為我們要移除 resource_type


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0021_remove_partial_payment_status'),
    ]

    operations = [
        # 先新增 mode 欄位（允許 null，用於資料遷移）
        migrations.AddField(
            model_name='learningresource',
            name='mode',
            field=models.CharField(
                choices=[
                    ('HANDOUT', '講義模式'),
                    ('ONLINE_QUIZ', '線上測驗模式'),
                    ('LEETCODE', '程式題模式'),
                    ('LISTENING_TEST', '聽力測驗模式'),
                    ('FLASHCARD', '單字卡模式')
                ],
                default='HANDOUT',
                max_length=20,
                null=True,
                verbose_name='模式類型'
            ),
        ),
        # 資料遷移：將 resource_type 轉換為 mode
        migrations.RunPython(
            code=migrate_resource_type_to_mode,
            reverse_code=reverse_migrate_mode_to_resource_type,
        ),
        # 移除 resource_type 欄位
        migrations.RemoveField(
            model_name='learningresource',
            name='resource_type',
        ),
        # 將 mode 設為不可為 null
        migrations.AlterField(
            model_name='learningresource',
            name='mode',
            field=models.CharField(
                choices=[
                    ('HANDOUT', '講義模式'),
                    ('ONLINE_QUIZ', '線上測驗模式'),
                    ('LEETCODE', '程式題模式'),
                    ('LISTENING_TEST', '聽力測驗模式'),
                    ('FLASHCARD', '單字卡模式')
                ],
                default='HANDOUT',
                max_length=20,
                verbose_name='模式類型'
            ),
        ),
        # 新增題目類型相關欄位
        migrations.AddField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(
                choices=[
                    ('SINGLE_CHOICE', '單選題'),
                    ('MULTIPLE_CHOICE', '多選題'),
                    ('FILL_IN_BLANK', '填充題'),
                    ('PROGRAMMING', '程式題'),
                    ('LISTENING', '聽力題')
                ],
                default='SINGLE_CHOICE',
                max_length=20,
                verbose_name='題目類型'
            ),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='options',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='選擇題的選項列表（JSON 格式）',
                null=True,
                verbose_name='選項'
            ),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='metadata',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='不同模式所需的額外資料（JSON 格式）',
                null=True,
                verbose_name='模式特定元資料'
            ),
        ),
    ]
