# Generated by Django 5.2.7 on 2025-12-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0022_add_mode_and_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='source',
            field=models.CharField(blank=True, default='九章自命題', help_text='題目來源，例如：九章自命題、學生錯題、學測、會考、統測、模擬考、基測等', max_length=100, null=True, verbose_name='題目來源'),
        ),
    ]
