# Generated by Django 5.2.7 on 2025-12-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0023_alter_questionbank_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresource',
            name='course',
        ),
        migrations.AddField(
            model_name='learningresource',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='learning_resources', to='cramschool.course', verbose_name='所屬課程'),
        ),
    ]
