# Generated by Django 5.2.7 on 2025-12-18 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0024_remove_learningresource_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='student_groups',
        ),
        migrations.RemoveField(
            model_name='assessmentsubmission',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='student_groups',
        ),
        migrations.RemoveField(
            model_name='assessmentsubmission',
            name='quiz',
        ),
        migrations.AlterModelOptions(
            name='assessmentsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': '教學資源提交', 'verbose_name_plural': '教學資源提交'},
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='learning_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='cramschool.learningresource', verbose_name='教學資源'),
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
