# Generated by Django 5.2.7 on 2025-12-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0025_remove_exam_course_remove_exam_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='tiptap_structure',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Tiptap JSON 結構'),
        ),
    ]
