# Generated by Django 5.2.7 on 2025-12-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0026_learningresource_tiptap_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttemplate',
            name='tiptap_structure',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Tiptap JSON 結構'),
        ),
    ]
