# Generated by Django 5.2.7 on 2025-12-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0027_contenttemplate_tiptap_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafee',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='當繳費狀態變為已繳費時的記錄時間', null=True, verbose_name='繳費時間'),
        ),
    ]
