# Generated by Django 5.2.7 on 2025-12-26 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0028_add_paid_at_to_extrafee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='group_type',
            field=models.CharField(choices=[('teaching', '教學群組'), ('tag', '標籤')], default='teaching', help_text='教學群組：老師用於個別化教學；標籤：會計用於標籤管理', max_length=20, verbose_name='群組類型'),
        ),
        migrations.AddIndex(
            model_name='studentgroup',
            index=models.Index(fields=['group_type'], name='cramschool__group_t_6d5afe_idx'),
        ),
    ]
