# Generated by Django 5.2.7 on 2025-12-29 02:48

from django.db import migrations, models


def convert_to_empty_json(apps, schema_editor):
    """
    將舊的 Markdown 資料轉換為空 JSON 物件 {}
    因為要轉換為 Tiptap JSON 格式，舊資料無法直接轉換
    用戶表示可以手動清除舊資料
    """
    QuestionBank = apps.get_model('cramschool', 'QuestionBank')
    # 將所有舊資料轉換為空 JSON 物件
    QuestionBank.objects.all().update(
        content='{}',
        correct_answer='{}'
    )


def reverse_convert(apps, schema_editor):
    """
    反向操作：不需要做任何事
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool', '0029_add_group_type_to_studentgroup'),
    ]

    operations = [
        # 先將舊資料轉換為空 JSON
        migrations.RunPython(convert_to_empty_json, reverse_convert),
        # 然後轉換欄位類型
        migrations.AlterField(
            model_name='questionbank',
            name='content',
            field=models.JSONField(default=dict, help_text='使用 Tiptap 編輯器創建的題目內容', verbose_name='題目內容 (Tiptap JSON)'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='correct_answer',
            field=models.JSONField(default=dict, help_text='使用 Tiptap 編輯器創建的正確答案', verbose_name='正確答案 (Tiptap JSON)'),
        ),
    ]
