# Generated by Django 5.2.7 on 2025-11-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('school', models.CharField(max_length=100, verbose_name='學校')),
                ('grade', models.CharField(max_length=50, verbose_name='年級')),
                ('contact', models.CharField(max_length=150, verbose_name='聯絡方式')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '學生資料',
                'verbose_name_plural': '學生資料',
                'ordering': ['name'],
            },
        ),
    ]
